language: php

sudo: required
dist: trusty

php:
  - 5.6

cache:
 directories:
  - $HOME/.composer/cache

before_install:
  ##############################################################################
  # Setup apache2
  ##############################################################################
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y --force-yes apache2 libapache2-mod-php5 php5-mysql php5-sqlite

  # Replace basedir in virtual host config
  - sed 's?%basedir%?'`pwd`'?' .travis/one.test.app.conf > .travis/one.test.app.conf
  - sed 's?%basedir%?'`pwd`'?' .travis/two.test.app.conf > .travis/two.test.app.conf

  # Define virtual host
  - sudo cp .travis/one.test.app.conf /etc/apache2/sites-available/one.test.app.conf
  - sudo cp .travis/two.test.app.conf /etc/apache2/sites-available/two.test.app.conf

  - ls /etc/apache2/sites-available
  - ls /etc/apache2/sites-enabled

  # Update our hosts
  - echo "127.0.0.1    one.test.app" | sudo tee -a /etc/hosts
  - echo "127.0.0.1    two.test.app" | sudo tee -a /etc/hosts

  # Enable mod rewrite
  - sudo a2enmod rewrite

  # Enable the sites
  - sudo a2ensite one.test.app.conf
  - sudo a2ensite two.test.app.conf

  # Restart apache
  - sudo /etc/init.d/apache2 restart

before_script:
  - cd website && composer self-update && composer install -n --prefer-source
  - curl http://one.test.app
  - curl http://two.test.app
